# SPDX-License-Identifier: GPL-2.0-only
#
# Makefile for kernel probes
#

obj-$(CONFIG_KPROBES)		+= core.o
obj-$(CONFIG_OPTPROBES)		+= opt.o
obj-$(CONFIG_KPROBES_ON_FTRACE)	+= ftrace.o
obj-$(CONFIG_KPROBES_NOP_OPT)	+= nop-opt/
